name: fittrack-backend
region: nyc

services:
  - name: api
    github:
      repo: Onahi7/fittrack-backend
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm run start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEON_DATABASE_URL
        value: ${NEON_DATABASE_URL}
        type: SECRET
      - key: FIREBASE_PROJECT_ID
        value: ${FIREBASE_PROJECT_ID}
        type: SECRET
      - key: FIREBASE_PRIVATE_KEY
        value: ${FIREBASE_PRIVATE_KEY}
        type: SECRET
      - key: FIREBASE_CLIENT_EMAIL
        value: ${FIREBASE_CLIENT_EMAIL}
        type: SECRET
      - key: CLOUDINARY_CLOUD_NAME
        value: ${CLOUDINARY_CLOUD_NAME}
        type: SECRET
      - key: CLOUDINARY_API_KEY
        value: ${CLOUDINARY_API_KEY}
        type: SECRET
      - key: CLOUDINARY_API_SECRET
        value: ${CLOUDINARY_API_SECRET}
        type: SECRET
      - key: RESEND_API_KEY
        value: ${RESEND_API_KEY}
        type: SECRET
      - key: ALLOWED_ORIGINS
        value: "https://fittrack.vercel.app"
      - key: FRONTEND_URL
        value: "https://fittrack.vercel.app"
